name: ci

on:
  push:
    branches: [master]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        id: hoge
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    if: needs.job1.outputs.hoge == 'success'
    steps:
      - run: echo "success"
