name: ci

on:
  push:
    branches: [master]

jobs:
  job1:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo "success"
