name: ci

on:
  push:
    branches: [master]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      hoge: ${{ steps.hoge.outcome }}
    steps:
      - id: hoge
        run: |
          ls
          echo 2
          exit 1
          echo 3
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo "${{ toJSON(needs.job1) }}"
      - run: echo "success"
