name: ci

on:
  push:
    branches: [master]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-output name=hoge::failure"
        id: hoge
        continue-on-error: true
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo ${{ toJSON(needs.job1) }}
      - run: echo "success"
